
using BenchmarkDotNet.Running;
using DruDe.Core.Buffers;
using DruDe.Core.CodeGen;
using DruDe.Core.CodeGen.Immediate;
using DruDe.Core.Perfs.Buffers;

#if RELEASE
BenchmarkRunner.Run<NoAllocationCodeWriterBenchmark>();
#else

// var test = new NoAllocationCodeWriterBenchmark();
// test.N = 100;
// test.Run();

Console.WriteLine("Start");
Test();

void Test()
{
   try
   {
      var builder = new CodeBuilder(
         stackalloc char[512],
         stackalloc char[128],
         3, ' ');
      
      builder.NameSpaceIm
         .EnableNullable()
         .AutoGeneratedComment()
            .Using("System.Test")
            .Using("System.A")
            .Using("System.B")
         .Set("My.NameSpace");

      builder.ClassIm;
      
      builder.Dispose();
   }
   catch (Exception error)
   {
      Console.WriteLine(error);
   }
}

#endif
